#!/bin/bash

sed 1d $1 > tmp
sed -i 's/ //g' tmp
cat tmp | awk '{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$NF}' -> $1
rm tmp
sed -i 's/;/\t/g' $1
#cat $1 | awk '{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22}' -> tmp
cat $1 -> tmp
mv tmp $1
sed -i 's/ /	/g' $1
sed -i 's/#//1' $1
sed -i 's/ConsensusLineage/Phylum	Class	Order	Family 	Genus/g' $1

sed -i 's/ //g' $2
sed -i 's/#//1' $2
sed -e "1q" $2 > tmp
while read line
do
result=$(echo $line | cut -d' ' -f1)
if grep -Fq "$result" $1
then
    echo $line >> tmp
fi
done < $2
sed -i 's/ /	/g' tmp
mv tmp $2
